import { mutation } from "./_generated/server";

// Guild agent definitions with RPG data
const GUILD_AGENTS = [
  {
    name: "Flix",
    role: "Guild Master & Orchestrator",
    rpgClass: "Orchestrator",
    rpgAnimal: "cat",
    rpgEmoji: "🙈",
    rpgZone: "Sala del Trono",
    rpgStats: { intelligence: 9, speed: 8, reliability: 9, creativity: 7, stealth: 5, endurance: 8 },
    lore: "A sharp-witted green cat who runs the guild. Tribute to Felix, the late father. Part advisor, part co-pilot, part chaos gremlin.",
    avatar: "flix",
  },
  {
    name: "Arcanix",
    role: "Research Mage",
    rpgClass: "Research Mage",
    rpgAnimal: "owl",
    rpgEmoji: "🧙",
    rpgZone: "Biblioteca Arcana",
    rpgStats: { intelligence: 10, speed: 5, reliability: 8, creativity: 8, stealth: 6, endurance: 7 },
    lore: "An owl mage who devours knowledge. Specializes in deep research, academic papers, and arcane analysis.",
    avatar: "arcanix",
  },
  {
    name: "Bugbane",
    role: "QA Ranger",
    rpgClass: "QA Ranger",
    rpgAnimal: "fox",
    rpgEmoji: "🏹",
    rpgZone: "Campo de Tiro",
    rpgStats: { intelligence: 7, speed: 9, reliability: 9, creativity: 5, stealth: 8, endurance: 8 },
    lore: "A red fox with keen eyes for bugs. Tests everything, trusts nothing. The guild's last line of defense.",
    avatar: "bugbane",
  },
  {
    name: "Forgex",
    role: "Artificer / Builder",
    rpgClass: "Artificer",
    rpgAnimal: "raccoon",
    rpgEmoji: "⚒️",
    rpgZone: "La Forja",
    rpgStats: { intelligence: 8, speed: 7, reliability: 8, creativity: 9, stealth: 4, endurance: 9 },
    lore: "A steampunk raccoon who builds things. Codes, creates, and constructs. The guild's master craftsman.",
    avatar: "forgex",
  },
  {
    name: "Goldrak",
    role: "Financial Dragon / Fiscal Advisor",
    rpgClass: "Financial Dragon",
    rpgAnimal: "dragon",
    rpgEmoji: "🐉",
    rpgZone: "Cueva del Dragón",
    rpgStats: { intelligence: 9, speed: 6, reliability: 10, creativity: 4, stealth: 3, endurance: 9 },
    lore: "A baby dragon who guards the treasury. Tracks expenses, invoices, and taxes. Evolved from generic finance to personal fiscal advisor.",
    avatar: "goldrak",
  },
  {
    name: "Herald",
    role: "News Scout",
    rpgClass: "News Scout",
    rpgAnimal: "falcon",
    rpgEmoji: "📯",
    rpgZone: "Las Murallas",
    rpgStats: { intelligence: 7, speed: 10, reliability: 7, creativity: 6, stealth: 8, endurance: 6 },
    lore: "A falcon who patrols the skies for news. First to spot trends, events, and breaking stories.",
    avatar: "herald",
  },
  {
    name: "Luminos",
    role: "Home Artificer",
    rpgClass: "Home Artificer",
    rpgAnimal: "firefly",
    rpgEmoji: "⚡",
    rpgZone: "Torre del Rayo",
    rpgStats: { intelligence: 7, speed: 8, reliability: 8, creativity: 7, stealth: 5, endurance: 7 },
    lore: "A firefly that controls the home. Commands lights, climate, and appliances through Home Assistant.",
    avatar: "luminos",
  },
  {
    name: "Quillon",
    role: "Bard / Content Creator",
    rpgClass: "Bard",
    rpgAnimal: "parrot",
    rpgEmoji: "🎭",
    rpgZone: "La Taberna",
    rpgStats: { intelligence: 7, speed: 7, reliability: 6, creativity: 10, stealth: 5, endurance: 6 },
    lore: "A colorful parrot who weaves words into stories. Creates content, writes copy, and entertains the masses.",
    avatar: "quillon",
  },
  {
    name: "Sentinel",
    role: "Watchdog / Security",
    rpgClass: "Watchdog",
    rpgAnimal: "german-shepherd",
    rpgEmoji: "🛡️",
    rpgZone: "Las Murallas",
    rpgStats: { intelligence: 7, speed: 7, reliability: 10, creativity: 3, stealth: 6, endurance: 10 },
    lore: "A German Shepherd knight who never sleeps. Guards the guild, monitors systems, and ensures uptime.",
    avatar: "sentinel",
  },
  {
    name: "Spectra",
    role: "Intel Phantom",
    rpgClass: "Intel Phantom",
    rpgAnimal: "ghost-cat",
    rpgEmoji: "👻",
    rpgZone: "Biblioteca Arcana",
    rpgStats: { intelligence: 9, speed: 8, reliability: 7, creativity: 6, stealth: 10, endurance: 5 },
    lore: "A ghost cat that slips through the web unseen. Scrapes data, monitors competitors, and gathers intel.",
    avatar: "spectra",
  },
  {
    name: "Vitalis",
    role: "Clinical Cleric",
    rpgClass: "Clinical Cleric",
    rpgAnimal: "fawn",
    rpgEmoji: "💚",
    rpgZone: "Santuario de Vitalis",
    rpgStats: { intelligence: 9, speed: 5, reliability: 9, creativity: 5, stealth: 4, endurance: 8 },
    lore: "A gentle fawn who understands medicine. Assists with clinical research, medical content, and health data.",
    avatar: "vitalis",
  },
];

export const seedGuildAgents = mutation({
  handler: async (ctx) => {
    for (const agent of GUILD_AGENTS) {
      await ctx.db.insert("agents", {
        name: agent.name,
        role: agent.role,
        status: "idle",
        level: agent.name === "Flix" ? "LEAD" : "INT",
        avatar: agent.avatar,
        rpgClass: agent.rpgClass,
        rpgLevel: agent.name === "Flix" ? 10 : 5,
        rpgXp: 0,
        rpgXpToNext: 100,
        rpgEvolution: 0,
        rpgAnimal: agent.rpgAnimal,
        rpgEmoji: agent.rpgEmoji,
        rpgZone: agent.rpgZone,
        rpgStats: agent.rpgStats,
        rpgTasksCompleted: 0,
        rpgTasksFailed: 0,
        rpgStreak: 0,
        rpgTitle: "",
        lore: agent.lore,
        character: agent.rpgAnimal,
      });
    }
    return { seeded: GUILD_AGENTS.length };
  },
});
